import * as cdk from 'aws-cdk-lib';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as cwActions from 'aws-cdk-lib/aws-cloudwatch-actions';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as subscriptions from 'aws-cdk-lib/aws-sns-subscriptions';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { Construct } from 'constructs';

export interface AppStackProps extends cdk.StackProps {
  vpc: ec2.Vpc;
  repository: ecr.Repository;
  albSecurityGroup: ec2.SecurityGroup;
  serviceSecurityGroup: ec2.SecurityGroup;
  database: rds.DatabaseInstance;
  uploadsBucket: s3.Bucket;
  distributionUrl: string;
}

/**
 * The Express API on Fargate, behind an Application Load Balancer.
 *
 * This is the only expensive stack - roughly $31/month if you leave one task
 * and the load balancer running around the clock. It imports from the other
 * three and nothing imports from it, so it can be destroyed and redeployed on
 * its own whenever you stop working:
 *
 *   npm run down     # deletes the ALB and the tasks
 *   npm run up       # brings them back in ~5 minutes
 */
export class AppStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: AppStackProps) {
    super(scope, id, props);

    const imageTag = String(this.node.tryGetContext('imageTag') ?? 'latest');
    const desiredCount = Number(this.node.tryGetContext('desiredCount') ?? 1);
    const scaling = String(this.node.tryGetContext('scaling')) === 'true';

    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: props.vpc,
      // Insights bills per metric. Plain CloudWatch logs and the ECS service
      // metrics are enough for the report; turn this up only if you need it.
      containerInsightsV2: ecs.ContainerInsights.DISABLED,
    });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
      cpu: 256,
      memoryLimitMiB: 512,
    });

    // Declared here rather than letting the log driver generate one, for two
    // reasons: the metric filters and saved queries below need something to
    // attach to, and a fixed name is what makes the group findable in the
    // console without first looking up a CloudFormation-generated suffix.
    //
    // One week of retention. Logs are billed on ingestion (~$0.63/GB here) plus
    // storage, and nothing in this project needs history older than the last
    // deploy. DESTROY so `npm run down` does not leave the group behind.
    // Held as a plain constant as well as on the construct: logGroup.logGroupName
    // is a CloudFormation token, and a CfnOutput description has to be a literal
    // string.
    const logGroupName = '/borrowit/api';

    const logGroup = new logs.LogGroup(this, 'ApiLogGroup', {
      logGroupName,
      retention: logs.RetentionDays.ONE_WEEK,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const dbSecret = props.database.secret!;

    // Signs the session cookie. Without it every login returns 500 with
    // "secretOrPrivateKey must have a value" - jwt.sign refuses an undefined
    // key rather than defaulting to anything.
    //
    // Generated by CloudFormation and never seen in plaintext by this repo, for
    // the same reason the database password is not: a value committed to
    // cdk.json or a .env is a value in git history. ~$0.40/month.
    //
    // Regenerated if AppStack is ever destroyed and redeployed, which
    // invalidates every issued token. That only means everyone logs in again.
    const jwtSecret = new secretsmanager.Secret(this, 'JwtSecret', {
      description: 'BorrowIt API token signing key',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'jwtSecret',
        passwordLength: 64,
        // The value is read back as an env var, so keep it to characters that
        // never need escaping anywhere in the chain.
        excludePunctuation: true,
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const container = taskDefinition.addContainer('api', {
      image: ecs.ContainerImage.fromEcrRepository(props.repository, imageTag),
      logging: ecs.LogDrivers.awsLogs({
        streamPrefix: 'borrowit',
        logGroup,
      }),
      environment: {
        PORT: '3456',
        NODE_ENV: 'production',
        // The AWS SDK does not get a region for free on Fargate and
        // uploadController reads this one explicitly.
        AWS_REGION: this.region,
        AWS_S3_BUCKET: props.uploadsBucket.bucketName,
        ASSET_BASE_URL: props.distributionUrl,
        FRONTEND_URL: props.distributionUrl,
      },
      // Injected from Secrets Manager at task start. db/index.js assembles
      // DATABASE_URL from these when it is not already set.
      secrets: {
        DB_HOST: ecs.Secret.fromSecretsManager(dbSecret, 'host'),
        DB_PORT: ecs.Secret.fromSecretsManager(dbSecret, 'port'),
        DB_USER: ecs.Secret.fromSecretsManager(dbSecret, 'username'),
        DB_PASSWORD: ecs.Secret.fromSecretsManager(dbSecret, 'password'),
        DB_NAME: ecs.Secret.fromSecretsManager(dbSecret, 'dbname'),
        // JWT_REFRESH_SECRET is deliberately not set. userController already
        // falls back to JWT_SECRET for refresh tokens, and a second secret is
        // another $0.40/month. Splitting them is a hardening step, not a fix.
        JWT_SECRET: ecs.Secret.fromSecretsManager(jwtSecret, 'jwtSecret'),
      },
      // Liveness only. ECS ignores the Dockerfile HEALTHCHECK, so it is
      // restated here. It deliberately does not touch the database - that is
      // the load balancer's job below.
      healthCheck: {
        command: [
          'CMD-SHELL',
          "node -e \"require('http').get('http://127.0.0.1:3456/health/live', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\"",
        ],
        interval: cdk.Duration.seconds(30),
        timeout: cdk.Duration.seconds(5),
        retries: 3,
        startPeriod: cdk.Duration.seconds(15),
      },
      // index.js drains for 5s then has 20s to finish in-flight requests.
      stopTimeout: cdk.Duration.seconds(30),
    });

    container.addPortMappings({ containerPort: 3456, protocol: ecs.Protocol.TCP });

    // Least privilege: the task may write objects to the uploads bucket and
    // nothing else. No static access keys anywhere.
    props.uploadsBucket.grantPut(taskDefinition.taskRole);

    const service = new ecs.FargateService(this, 'Service', {
      cluster,
      taskDefinition,
      desiredCount,
      // Public subnet + public IP is what lets us skip the NAT Gateway. Inbound
      // is still restricted to the ALB by the service security group.
      assignPublicIp: true,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroups: [props.serviceSecurityGroup],
      // A deployment that fails its health checks rolls back on its own instead
      // of sitting there broken.
      circuitBreaker: { rollback: true },
      // Lets you open a shell inside a running task with `aws ecs
      // execute-command`. That is how the schema gets loaded, since RDS has no
      // public endpoint, and it is the fastest way to debug a task that will
      // not start. CDK adds the required SSM permissions to the task role.
      enableExecuteCommand: true,
      // At desiredCount 1 this lets ECS stop the old task before starting the
      // new one, so a deploy never needs to pay for two tasks. The tradeoff is
      // a few seconds of downtime per deploy.
      minHealthyPercent: 50,
      maxHealthyPercent: 200,
    });

    const alb = new elbv2.ApplicationLoadBalancer(this, 'LoadBalancer', {
      vpc: props.vpc,
      internetFacing: true,
      securityGroup: props.albSecurityGroup,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
    });

    const listener = alb.addListener('Listener', {
      port: 80,
      // Ingress is already defined on the security group in FoundationStack.
      open: false,
    });

    const targetGroup = listener.addTargets('AppTargets', {
      port: 3456,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targets: [service],
      // Must exceed DRAIN_DELAY_MS (5s) in index.js, or the task closes its
      // socket while the balancer is still routing to it.
      deregistrationDelay: cdk.Duration.seconds(15),
      healthCheck: {
        // Readiness, not liveness: this one runs SELECT 1, so a task that has
        // lost its database connection is pulled out of rotation.
        path: '/health',
        interval: cdk.Duration.seconds(30),
        timeout: cdk.Duration.seconds(5),
        healthyThresholdCount: 2,
        unhealthyThresholdCount: 3,
      },
    });

    if (scaling) {
      // Off by default because a scale-out event doubles the compute bill.
      // Turn it on for the high-availability demo: -c scaling=true
      const scalable = service.autoScaleTaskCount({
        minCapacity: 1,
        maxCapacity: 3,
      });
      scalable.scaleOnCpuUtilization('CpuScaling', {
        targetUtilizationPercent: 65,
        scaleInCooldown: cdk.Duration.seconds(120),
        scaleOutCooldown: cdk.Duration.seconds(60),
      });
    }

    // ---------------------------------------------------------------------
    // Observability
    //
    // Lives in AppStack rather than a fifth stack because a separate stack
    // would have to import from AppStack, and nothing is allowed to do that -
    // that one-way dependency is what keeps `npm run down` working. The cost of
    // putting it here is that tearing the app down also removes the alarms,
    // which is fine: they have nothing to watch at that point.
    //
    // Billed monthly: one dashboard (~$3), seven standard alarms (~$0.10 each)
    // and two custom metrics from the log filters (~$0.30 each). SNS email
    // delivery is effectively free at this volume. Metric filters themselves
    // are free - they run on logs already being ingested.
    // ---------------------------------------------------------------------

    // Five minutes everywhere. Anything finer multiplies the metric-storage
    // cost without telling you more about a one-task service.
    const period = cdk.Duration.minutes(5);

    // Turns log lines into metrics, which is what makes logs alarmable.
    //
    // Deliberately a text match, not a JSON one: index.js emits structured
    // errors, but the console.error calls scattered through the controllers
    // ("Login error:", "Auth middleware error:") are plain strings and are
    // still the majority of what actually gets logged when something breaks.
    // A JSON filter would silently miss all of them.
    const errorLogMetric = logGroup
      .addMetricFilter('ErrorLogFilter', {
        filterPattern: logs.FilterPattern.anyTerm('ERROR', 'Error:', 'error:'),
        metricNamespace: 'BorrowIt',
        metricName: 'ApiErrorLogCount',
        metricValue: '1',
        // Emit an explicit 0 when logs arrive with no error in them, so the
        // alarm can tell "quiet" apart from "no data".
        defaultValue: 0,
      })
      .metric({ period, statistic: 'Sum' });

    // The structured half: request lines carry a numeric status, so 5xx can be
    // counted exactly. No alarm on this one - Target5xxAlarm above already
    // watches the same failures from the load balancer's side, and two alarms
    // on one condition just means two emails. This feeds the dashboard so you
    // can see which requests the ALB counter is referring to.
    const serverErrorMetric = logGroup
      .addMetricFilter('ServerErrorFilter', {
        filterPattern: logs.FilterPattern.numberValue('$.status', '>=', 500),
        metricNamespace: 'BorrowIt',
        metricName: 'ApiServerErrorCount',
        metricValue: '1',
        defaultValue: 0,
      })
      .metric({ period, statistic: 'Sum' });

    const alarmEmail = this.node.tryGetContext('alarmEmail');

    // Created either way so alarms always have somewhere to publish. A topic
    // with no subscription costs nothing; pass -c alarmEmail=you@example.com to
    // actually receive anything, then confirm the subscription by email.
    const alarmTopic = new sns.Topic(this, 'AlarmTopic', {
      displayName: 'BorrowIt alarms',
    });

    if (alarmEmail) {
      alarmTopic.addSubscription(
        new subscriptions.EmailSubscription(String(alarmEmail)),
      );
    }

    const alarmAction = new cwActions.SnsAction(alarmTopic);

    const alarms: cloudwatch.Alarm[] = [
      // The single most useful alarm here: at desiredCount 1, one unhealthy
      // target means the API is down, not degraded.
      new cloudwatch.Alarm(this, 'UnhealthyTargetsAlarm', {
        alarmName: `${this.stackName}-unhealthy-targets`,
        alarmDescription: 'No healthy task behind the load balancer',
        metric: targetGroup.metrics.unhealthyHostCount({ period }),
        threshold: 1,
        evaluationPeriods: 1,
        comparisonOperator:
          cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
        // A task that is gone reports no data at all, which must not read as
        // healthy.
        treatMissingData: cloudwatch.TreatMissingData.BREACHING,
      }),

      new cloudwatch.Alarm(this, 'Target5xxAlarm', {
        alarmName: `${this.stackName}-api-5xx`,
        alarmDescription: 'Express is returning server errors',
        metric: targetGroup.metrics.httpCodeTarget(
          elbv2.HttpCodeTarget.TARGET_5XX_COUNT,
          { period, statistic: 'Sum' },
        ),
        threshold: 5,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        // No requests in the window is not an error.
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),

      new cloudwatch.Alarm(this, 'ServiceCpuAlarm', {
        alarmName: `${this.stackName}-service-cpu`,
        alarmDescription: 'Fargate task CPU sustained above 80%',
        metric: service.metricCpuUtilization({ period }),
        threshold: 80,
        evaluationPeriods: 3,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),

      new cloudwatch.Alarm(this, 'ServiceMemoryAlarm', {
        alarmName: `${this.stackName}-service-memory`,
        alarmDescription: 'Fargate task memory above 85% - 512 MiB is not much',
        metric: service.metricMemoryUtilization({ period }),
        threshold: 85,
        evaluationPeriods: 3,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),

      new cloudwatch.Alarm(this, 'DatabaseCpuAlarm', {
        alarmName: `${this.stackName}-db-cpu`,
        alarmDescription: 'db.t4g.micro CPU sustained above 80%',
        metric: props.database.metricCPUUtilization({ period }),
        threshold: 80,
        evaluationPeriods: 3,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),

      // Storage autoscaling is deliberately pinned off, so running out of disk
      // is a real failure mode rather than something RDS quietly fixes.
      new cloudwatch.Alarm(this, 'DatabaseStorageAlarm', {
        alarmName: `${this.stackName}-db-storage`,
        alarmDescription: 'Less than 2 GiB free on a 20 GiB volume that cannot grow',
        metric: props.database.metricFreeStorageSpace({ period }),
        threshold: 2 * 1024 * 1024 * 1024,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),

      // The one alarm that comes from logs rather than from infrastructure
      // metrics. It catches failures that never become a 5xx - a bad database
      // query that gets caught and returned as a 400, an email that will not
      // send - which the ALB metrics cannot see by definition.
      //
      // The threshold is a guess, not a measurement: a handful of failed logins
      // an hour is normal, twenty errors in five minutes is not. Watch it for a
      // few days and move it rather than leaving it noisy.
      new cloudwatch.Alarm(this, 'ErrorLogAlarm', {
        alarmName: `${this.stackName}-error-logs`,
        alarmDescription: 'Unusual number of errors written to the API log',
        metric: errorLogMetric,
        threshold: 20,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }),
    ];

    alarms.forEach((alarm) => alarm.addAlarmAction(alarmAction));

    const dashboard = new cloudwatch.Dashboard(this, 'Dashboard', {
      dashboardName: 'BorrowIt',
      defaultInterval: cdk.Duration.hours(3),
    });

    dashboard.addWidgets(
      new cloudwatch.GraphWidget({
        title: 'Requests and errors',
        width: 12,
        left: [targetGroup.metrics.requestCount({ period, statistic: 'Sum' })],
        right: [
          targetGroup.metrics.httpCodeTarget(
            elbv2.HttpCodeTarget.TARGET_5XX_COUNT,
            { period, statistic: 'Sum', label: '5xx' },
          ),
          alb.metrics.httpCodeElb(elbv2.HttpCodeElb.ELB_5XX_COUNT, {
            period,
            statistic: 'Sum',
            label: 'ELB 5xx',
          }),
        ],
      }),
      new cloudwatch.GraphWidget({
        title: 'Latency (p50 / p95)',
        width: 12,
        left: [
          targetGroup.metrics.targetResponseTime({ period, statistic: 'p50' }),
          targetGroup.metrics.targetResponseTime({ period, statistic: 'p95' }),
        ],
      }),
    );

    dashboard.addWidgets(
      new cloudwatch.GraphWidget({
        title: 'Fargate task',
        width: 12,
        left: [
          service.metricCpuUtilization({ period, label: 'CPU %' }),
          service.metricMemoryUtilization({ period, label: 'Memory %' }),
        ],
      }),
      new cloudwatch.GraphWidget({
        title: 'Database',
        width: 12,
        left: [props.database.metricCPUUtilization({ period, label: 'CPU %' })],
        right: [
          props.database.metricDatabaseConnections({ period, label: 'Connections' }),
          props.database.metricFreeStorageSpace({ period, label: 'Free storage' }),
        ],
      }),
    );

    dashboard.addWidgets(
      new cloudwatch.GraphWidget({
        title: 'Healthy targets',
        width: 12,
        left: [
          targetGroup.metrics.healthyHostCount({ period }),
          targetGroup.metrics.unhealthyHostCount({ period }),
        ],
      }),
      new cloudwatch.GraphWidget({
        title: 'Errors in logs',
        width: 12,
        left: [
          errorLogMetric.with({ label: 'Error lines' }),
          serverErrorMetric.with({ label: '5xx responses' }),
        ],
      }),
    );

    // The actual log lines, on the same screen as the graphs. Insights charges
    // per GB scanned, so both widgets are capped and time-bounded by the
    // dashboard's 3-hour default interval rather than scanning the full week.
    dashboard.addWidgets(
      new cloudwatch.LogQueryWidget({
        title: 'Recent errors',
        logGroupNames: [logGroup.logGroupName],
        width: 12,
        height: 6,
        queryLines: [
          'fields @timestamp, @message',
          'filter @message like /(?i)(error|exception)/',
          'sort @timestamp desc',
          'limit 20',
        ],
      }),
      new cloudwatch.LogQueryWidget({
        title: 'Slowest routes',
        logGroupNames: [logGroup.logGroupName],
        width: 12,
        height: 6,
        // Reads the fields the request logger emits. Health checks are already
        // excluded at the source, so this is real traffic only.
        queryLines: [
          'fields @timestamp, method, path, durationMs',
          "filter type = 'request'",
          'stats count(*) as calls, avg(durationMs) as avgMs, max(durationMs) as maxMs by method, path',
          'sort avgMs desc',
          'limit 15',
        ],
      }),
    );

    // Saved Insights queries. Free, and they turn "I need to debug this" into a
    // dropdown pick instead of writing query syntax from memory at the time it
    // matters. They show up under Logs Insights > Saved queries > BorrowIt.
    //
    // String literals are in SINGLE quotes throughout. Insights reads a
    // double-quoted token as a field name, so `type = "request"` compares the
    // field `type` against the field `request` and returns zero rows without
    // erroring - a filter that looks right and quietly matches nothing.
    const savedQueries: Record<string, string[]> = {
      'Errors with stack traces': [
        'fields @timestamp, path, message, stack',
        "filter level = 'error'",
        'sort @timestamp desc',
        'limit 50',
      ],
      'Slowest requests': [
        'fields @timestamp, method, path, status, durationMs',
        "filter type = 'request'",
        'sort durationMs desc',
        'limit 50',
      ],
      'Status code breakdown': [
        "filter type = 'request'",
        'stats count(*) by status',
        'sort status asc',
      ],
      'Traffic by route': [
        "filter type = 'request'",
        'stats count(*) as calls, avg(durationMs) as avgMs by method, path',
        'sort calls desc',
      ],
      // Not JSON-dependent: this one still works for the plain-text
      // console.error lines in the controllers.
      'Raw error lines': [
        'fields @timestamp, @logStream, @message',
        'filter @message like /(?i)error/',
        'sort @timestamp desc',
        'limit 100',
      ],
    };

    Object.entries(savedQueries).forEach(([name, queryLines], i) => {
      new logs.CfnQueryDefinition(this, `Query${i}`, {
        name: `BorrowIt/${name}`,
        logGroupNames: [logGroup.logGroupName],
        queryString: queryLines.join('\n| '),
      });
    });

    new cdk.CfnOutput(this, 'DashboardUrl', {
      value: `https://${this.region}.console.aws.amazon.com/cloudwatch/home?region=${this.region}#dashboards:name=${dashboard.dashboardName}`,
    });
    new cdk.CfnOutput(this, 'AlarmTopicArn', { value: alarmTopic.topicArn });
    new cdk.CfnOutput(this, 'LogGroupName', {
      value: logGroup.logGroupName,
      description: `Follow with: aws logs tail ${logGroupName} --follow`,
    });

    // Published so FrontendStack can find the load balancer without importing
    // from this stack. A CloudFormation export would reverse the dependency
    // direction and make `cdk destroy BorrowitApp` fail on a value still in
    // use; a parameter is read out of band, so the one-way rule survives.
    //
    // FrontendStack reads this at synth time, which bakes the literal DNS name
    // into its template - so when the load balancer is replaced, the template
    // genuinely changes and CloudFormation performs the update. A deploy-time
    // `{{resolve:ssm:...}}` reference would look tidier and be wrong: with an
    // otherwise identical template CloudFormation reports "no changes" and
    // quietly keeps pointing at the load balancer that no longer exists.
    //
    // Standard parameters are free.
    new ssm.StringParameter(this, 'AlbDnsParameter', {
      parameterName: '/borrowit/alb-dns',
      stringValue: alb.loadBalancerDnsName,
      description: 'ALB behind the CloudFront /api/* behaviour. Read by BorrowitFrontend.',
    });

    new cdk.CfnOutput(this, 'ApiUrl', { value: `http://${alb.loadBalancerDnsName}` });
    new cdk.CfnOutput(this, 'HealthUrl', {
      value: `http://${alb.loadBalancerDnsName}/health`,
    });
    new cdk.CfnOutput(this, 'ClusterName', { value: cluster.clusterName });
    new cdk.CfnOutput(this, 'ServiceName', { value: service.serviceName });
  }
}
