-- BorrowIt database schema
--
-- RECONSTRUCTED from the application code, not dumped from the original
-- database. Column names and relationships are derived from the SQL in
-- models/, the INSERT column lists in db/seed_data.sql, and the response
-- schemas in openapi.yaml. Types and constraints are inferred, so review the
-- notes marked ASSUMPTION before treating this as authoritative.
--
-- Apply with:  node scripts/run-sql.js db/schema.sql

-- ---------------------------------------------------------------------------
-- Extensions and helpers
-- ---------------------------------------------------------------------------

-- Keeps updated_at honest. Several models set it explicitly and several do not
-- (Product.updateProduct, for one), which is why this is a trigger rather than
-- a column default.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- User
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "User" (
  user_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username           text        NOT NULL UNIQUE,
  email              text        NOT NULL UNIQUE,
  password           text        NOT NULL,
  full_name          text,
  phone              text,
  avatar_url         text,
  address            text,
  role               text        NOT NULL DEFAULT 'customer',
  status             text        NOT NULL DEFAULT 'pending',
  rating             numeric(3,2),
  total_orders       integer     NOT NULL DEFAULT 0,
  email_verified     boolean     NOT NULL DEFAULT false,
  verification_token text,
  token_expires      timestamptz,
  reset_token        text,
  reset_expires      timestamptz,
  last_login_at      timestamptz,
  created_at         timestamptz NOT NULL DEFAULT NOW(),
  updated_at         timestamptz NOT NULL DEFAULT NOW()
);

-- role   IN ('customer', 'seller', 'admin')
-- status IN ('active', 'suspended', 'pending')
--
-- These were CHECK constraints originally - db/drop_all_constraints.sql drops
-- "User_role_check" and "User_status_check" by name. They are deliberately not
-- recreated here, because that script exists precisely because the app outgrew
-- them. Documented as comments so the intent survives.

CREATE INDEX IF NOT EXISTS user_role_idx   ON "User" (role);
CREATE INDEX IF NOT EXISTS user_status_idx ON "User" (status);

DROP TRIGGER IF EXISTS user_set_updated_at ON "User";
CREATE TRIGGER user_set_updated_at
  BEFORE UPDATE ON "User"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Product
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Product" (
  product_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id       integer     NOT NULL REFERENCES "User" (user_id) ON DELETE CASCADE,
  name            text        NOT NULL,
  description     text,
  category        text        NOT NULL,
  price_per_day   numeric(12,2) NOT NULL,
  sale_percentage integer     NOT NULL DEFAULT 0,
  -- ASSUMPTION: a Postgres text array, not jsonb. Order.js uses `p.images[1]`
  -- (array subscript) and mapOrderRow parses the `{a,b,c}` array literal, and
  -- seed_data.sql inserts ARRAY[...]. See the known-issue note at the bottom.
  images          text[]      NOT NULL DEFAULT '{}',
  location        text,
  status          text        NOT NULL DEFAULT 'available',
  condition       text        NOT NULL DEFAULT 'good',
  rating          numeric(3,2),
  total_reviews   integer     NOT NULL DEFAULT 0,
  total_rentals   integer     NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);

-- category  was IN ('Electronics','Clothes','Furniture','Sports','Books','Tools','Vehicles','Other')
-- status    IN ('available', 'rented', 'unavailable')
-- condition IN ('new', 'like_new', 'good', 'fair', 'poor')
--
-- Same story as User: db/drop_category_constraint.sql exists specifically to
-- remove "Product_category_check" so arbitrary categories could be inserted.
-- Not recreated. min_rental_days, max_rental_days and deposit are intentionally
-- absent - db/migration_remove_product_fields.sql drops them, even though they
-- still appear in openapi.yaml.

CREATE INDEX IF NOT EXISTS product_seller_idx   ON "Product" (seller_id);
CREATE INDEX IF NOT EXISTS product_category_idx ON "Product" (category);
CREATE INDEX IF NOT EXISTS product_status_idx   ON "Product" (status);
CREATE INDEX IF NOT EXISTS product_created_idx  ON "Product" (created_at DESC);

DROP TRIGGER IF EXISTS product_set_updated_at ON "Product";
CREATE TRIGGER product_set_updated_at
  BEFORE UPDATE ON "Product"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Order
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Order" (
  order_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number     text        NOT NULL UNIQUE,
  customer_id      integer     NOT NULL REFERENCES "User" (user_id) ON DELETE RESTRICT,
  seller_id        integer     NOT NULL REFERENCES "User" (user_id) ON DELETE RESTRICT,
  product_id       integer     NOT NULL REFERENCES "Product" (product_id) ON DELETE RESTRICT,
  product_size     text,
  product_color    text,
  -- Text, not integer. seeder.js, seed_data.sql and the frontend fixture in
  -- data/ordersData.js all write '7 days'. Order.js parseInt()s it back out to
  -- compute subtotal, which is why the free-text form survives. See the
  -- inconsistency note at the bottom of this file.
  rental_period    text        NOT NULL DEFAULT '1',
  quantity         integer     NOT NULL DEFAULT 1,
  unit_price       numeric(12,2) NOT NULL DEFAULT 0,
  status           text        NOT NULL DEFAULT 'ordered',
  placed_at        timestamptz NOT NULL DEFAULT NOW(),
  subtotal         numeric(12,2) NOT NULL DEFAULT 0,
  tax              numeric(12,2) NOT NULL DEFAULT 0,
  total_amount     numeric(12,2) NOT NULL DEFAULT 0,
  shipping_address jsonb,
  timeline         jsonb       NOT NULL DEFAULT '[]'::jsonb,
  receiving_info   jsonb,
  return_info      jsonb,
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT NOW(),
  updated_at       timestamptz NOT NULL DEFAULT NOW()
);

-- status IN ('ordered','shipping','using','return','checking','completed')
-- (models/Order.js ORDER_STATUS_VALUES). Enforced in application code.
--
-- ASSUMPTION: ON DELETE RESTRICT on product_id and the two user columns. That
-- makes deleteProduct() fail for a product that has orders, rather than
-- silently destroying order history. If you would rather deletes cascade, this
-- is the line to change - but think about it first.

CREATE INDEX IF NOT EXISTS order_customer_idx ON "Order" (customer_id);
CREATE INDEX IF NOT EXISTS order_seller_idx   ON "Order" (seller_id);
CREATE INDEX IF NOT EXISTS order_product_idx  ON "Order" (product_id);
CREATE INDEX IF NOT EXISTS order_status_idx   ON "Order" (status);
CREATE INDEX IF NOT EXISTS order_placed_idx   ON "Order" (placed_at DESC);

DROP TRIGGER IF EXISTS order_set_updated_at ON "Order";
CREATE TRIGGER order_set_updated_at
  BEFORE UPDATE ON "Order"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Review
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Review" (
  review_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_id        integer     NOT NULL REFERENCES "User" (user_id) ON DELETE CASCADE,
  product_id         integer     NOT NULL REFERENCES "Product" (product_id) ON DELETE CASCADE,
  order_id           integer     REFERENCES "Order" (order_id) ON DELETE SET NULL,
  satisfaction       text        NOT NULL,
  satisfaction_score integer     NOT NULL,
  -- {fit, quality, easeOfUse, style, worthThePrice} booleans
  experience         jsonb       NOT NULL DEFAULT '{}'::jsonb,
  highlights         text,
  improvements       text,
  -- Array of image URLs. jsonb here, unlike Product.images - Review.js writes
  -- it with tx.json().
  photos             jsonb       NOT NULL DEFAULT '[]'::jsonb,
  photos_count       integer     NOT NULL DEFAULT 0,
  submitted_at       timestamptz NOT NULL DEFAULT NOW(),
  created_at         timestamptz NOT NULL DEFAULT NOW(),
  updated_at         timestamptz NOT NULL DEFAULT NOW()
);

-- satisfaction IN ('loved-it','liked-it','it-was-okay','not-great','terrible')
-- mapping to satisfaction_score 5..1 (models/Review.js SATISFACTION_SCORES).

CREATE INDEX IF NOT EXISTS review_product_idx   ON "Review" (product_id);
CREATE INDEX IF NOT EXISTS review_reviewer_idx  ON "Review" (reviewer_id);
CREATE INDEX IF NOT EXISTS review_order_idx     ON "Review" (order_id);
CREATE INDEX IF NOT EXISTS review_submitted_idx ON "Review" (submitted_at DESC);

DROP TRIGGER IF EXISTS review_set_updated_at ON "Review";
CREATE TRIGGER review_set_updated_at
  BEFORE UPDATE ON "Review"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Cart / CartItem
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Cart" (
  -- Primary key is `id`, not `cart_id` - models/Cart.js filters on `id`.
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        integer     NOT NULL REFERENCES "User" (user_id) ON DELETE CASCADE,
  status         text        NOT NULL DEFAULT 'open',
  total_amount   numeric(12,2) NOT NULL DEFAULT 0,
  total_quantity integer     NOT NULL DEFAULT 0,
  -- "order" is a reserved word and must stay quoted everywhere. It is a count
  -- of line items, not a sort key.
  "order"        integer     NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT NOW(),
  updated_at     timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS cart_user_idx ON "Cart" (user_id);
-- getOpenCartByUserId assumes at most one open cart per user.
CREATE UNIQUE INDEX IF NOT EXISTS cart_one_open_per_user_idx
  ON "Cart" (user_id) WHERE status = 'open';

DROP TRIGGER IF EXISTS cart_set_updated_at ON "Cart";
CREATE TRIGGER cart_set_updated_at
  BEFORE UPDATE ON "Cart"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS "CartItem" (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id     integer     NOT NULL REFERENCES "Cart" (id) ON DELETE CASCADE,
  product_id  integer     NOT NULL REFERENCES "Product" (product_id) ON DELETE CASCADE,
  -- Price after sale_percentage is applied, not the list price.
  unit_price  numeric(12,2) NOT NULL,
  quantity    integer     NOT NULL DEFAULT 1,
  -- {product_name, images} snapshot taken at add-to-cart time.
  metadata    jsonb       NOT NULL DEFAULT '{}'::jsonb,
  rent_time   integer     NOT NULL DEFAULT 1,
  total_price numeric(12,2) NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT NOW(),
  updated_at  timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS cartitem_cart_idx    ON "CartItem" (cart_id);
CREATE INDEX IF NOT EXISTS cartitem_product_idx ON "CartItem" (product_id);

DROP TRIGGER IF EXISTS cartitem_set_updated_at ON "CartItem";
CREATE TRIGGER cartitem_set_updated_at
  BEFORE UPDATE ON "CartItem"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Report
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Report" (
  report_id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporting_user_id       integer     NOT NULL REFERENCES "User" (user_id) ON DELETE CASCADE,
  reported_user_id        integer     NOT NULL REFERENCES "User" (user_id) ON DELETE CASCADE,
  -- Denormalised on purpose: the model writes both usernames alongside the ids
  -- so a report still reads correctly after a rename.
  reporting_user_username text,
  reported_user_username  text,
  reason                  text        NOT NULL,
  reason_extended         text,
  image                   text,
  report_date             timestamptz NOT NULL DEFAULT NOW(),
  status                  text        NOT NULL DEFAULT 'pending',
  action                  text,
  unsuspend_date          timestamptz,
  action_reason           text,
  mod_note                text,
  resolve_date            timestamptz
);

CREATE INDEX IF NOT EXISTS report_status_idx   ON "Report" (status);
CREATE INDEX IF NOT EXISTS report_reported_idx ON "Report" (reported_user_id);
CREATE INDEX IF NOT EXISTS report_date_idx     ON "Report" (report_date DESC);

-- ---------------------------------------------------------------------------
-- get_product_avg_rating
-- ---------------------------------------------------------------------------
--
-- Required. models/Product.js and models/Order.js call this in nearly every
-- SELECT, so product listing, product detail, search and the whole order API
-- fail without it. Returns 0 rather than NULL for an unreviewed product,
-- because searchProducts compares the result with >= in a HAVING clause.

CREATE OR REPLACE FUNCTION get_product_avg_rating(p_product_id integer)
RETURNS numeric
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(ROUND(AVG(satisfaction_score)::numeric, 2), 0)
  FROM "Review"
  WHERE product_id = p_product_id;
$$;

-- ---------------------------------------------------------------------------
-- Known issue found while reconstructing
-- ---------------------------------------------------------------------------
--
-- models/Review.js getReviewsByUser selects `p.images ->> 0 AS primary_image`.
-- The ->> operator is jsonb-only, and Product.images is text[] everywhere else
-- in the codebase, so that query raises:
--
--   operator does not exist: text[] ->> integer
--
-- The fix is `p.images[1] AS primary_image`, matching models/Order.js. Left
-- unchanged here because this file only defines the schema.
